services:
  pg-0:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/soldevelo/postgresql-repmgr:17.6.0-debian-12-r0
    container_name: "pg-0"
    ports:
      - 5433:5432
    volumes:
      - ./pg-data/data-0:/bitnami/postgresql
    networks:
      - pgpool
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    restart: always
  pg-1:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/soldevelo/postgresql-repmgr:17.6.0-debian-12-r0
    container_name: "pg-1"
    ports:
      - 5434:5432
    volumes:
      - ./pg-data/data-1:/bitnami/postgresql
    networks:
      - pgpool
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_USERNAME=${REPMGR_USERNAME}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
    restart: always
  pgpool:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/soldevelo/pgpool:4.6.3-debian-12-r0
    container_name: "pgpool"
    ports:
      - 5432:5432
    volumes:
      - ./pool-conf/myconf.conf:/config/myconf.conf
    networks: 
      - pgpool
      - redrock
    environment:
      - PGPOOL_USER_CONF_FILE=/config/myconf.conf
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=${REPMGR_USERNAME}
      - PGPOOL_SR_CHECK_PASSWORD=${REPMGR_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_POSTGRES_CUSTOM_USERS=${POSTGRESQL_USERNAME}
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${POSTGRESQL_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pgpool:
    external: true
  redrock:
    external: true
